# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
#     the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#     find the sum of the even-valued terms.

secuence = [1,2,3]
lastnumber  = 0
fibsum = 6


while (fibsum < 4000000):
    lastnumber = secuence[-1]
    nextitem = secuence[-1] + secuence[-2]
    secuence.append(nextitem)
    fibsum += nextitem

print(fibsum)


