# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
#     the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#     find the sum of the even-valued terms.

sum = 0
num1 = 1
num2 = 2

while num1 < 4000000:
    if num1 % 2 == 0:
        sum += num1
    num2 = num1 + num2
    num1 = num2 - num1

print(sum)

#4613732
#Congratulations, the answer you gave to problem 2 is correct.
#You are the 475314th person to have solved this problem.


